# MissileToad component registration
include_component(missile_toad/core/components/transform.component.hpp src/core/components/transform.component.cpp missiletoad::core::TransformComponent)
include_component(missile_toad/core/components/camera_2d.component.hpp src/core/components/camera_2d.component.cpp missiletoad::core::Camera2dComponent)
include_component(missile_toad/core/components/sprite.component.hpp src/core/components/sprite.component.cpp missiletoad::core::SpriteComponent)
include_component(missile_toad/core/components/rigidbody_2d.component.hpp src/core/components/rigidbody_2d.component.cpp missiletoad::core::Rigidbody2dComponent)
include_component(missile_toad/core/components/box_collider_2d.component.hpp src/core/components/box_collider_2d.component.cpp missiletoad::core::BoxCollider2dComponent)
include_component(missile_toad/core/components/sprite_animation.component.hpp src/core/components/sprite_animation.component.cpp missiletoad::core::SpriteAnimationComponent)
include_component(missile_toad/core/components/audio.component.hpp src/core/components/audio.component.cpp missiletoad::core::AudioComponent)
include_component(missile_toad/core/components/collision2d.component.hpp src/core/components/collision2d.component.cpp missiletoad::core::Collision2dComponent)
include_component(missile_toad/game/components/player.component.hpp src/game/components/player.component.cpp missiletoad::game::PlayerComponent)
