name: Build Switch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    name: Build for switch
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v3
      - name: Install newest CMake
        # https://github.com/Kitware/CMake/releases/download/v3.27.3/cmake-3.27.3-linux-x86_64.sh
        run: |
          wget "https://github.com/Kitware/CMake/releases/download/v3.27.3/cmake-3.27.3-linux-x86_64.sh"
          chmod +x cmake-3.27.3-linux-x86_64.sh
          sudo ./cmake-3.27.3-linux-x86_64.sh --skip-license --prefix=/usr
      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install ninja-build

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
          -DCMAKE_BUILD_TYPE=Debug
          -DPLATFORM="Nintendo Switch"
          -DDCMAKE_CXX_FLAGS="-fexceptions"
          -DBUILD_TESTS=OFF
          -G Ninja
          -S .

      - name: Build
        run: cmake --build build --config Debug