name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run:  |
          sudo deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          sudo deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          sudo apt update && sudo apt install -y clang-format-17
          sudo ln -s /usr/bin/clang-format-17 /usr/bin/clang-format
      - name: Format
        run: |
          find missile_toad -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
          find tests -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
        
