name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt install -y clang-format
      - name: Format
        run: |
          find missile_toad -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
          find tests -iname *.hpp -o -iname *.cpp | xargs clang-format -i -style=file --dry-run --Werror
        
